/elevation_mapping_node:
  ros__parameters:
    pointcloud_channel_fusions:
      rgb: "color"
      default: "average"

    image_channel_fusions:
      rgb: "color"
      default: "exponential"
      feat_.*: "exponential"
      sem_.*: "exponential"

    publishers:
      elevation_map_raw:
        layers: ["elevation", "traversability", "variance", "upper_bound"]
        basic_layers: ["elevation", "traversability"]
        fps: 5.0

      elevation_map_recordable:
        layers: ["elevation", "traversability", "variance"]
        basic_layers: ["elevation", "traversability"]
        fps: 2.0

      filtered_elevation_map:
        layers: ["inpaint", "smooth", "min_filter", "max_filter", "upper_bound", "min_smooth_filter"]
        basic_layers: ["inpaint"]
        fps: 5.0

    subscribers:
      Livox:
        topic_name: "/robot/dlio/odom_node/pointcloud/deskewed_self_filtered"
        data_type: "pointcloud"
        ray_source_frame: "livox_frame"
